name: Fiyat Takip Otomasyonu

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Depoyu Indir
        uses: actions/checkout@v4

      - name: Python Kurulumu
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Gerekli Kutuphaneleri Yukle
        run: pip install requests beautifulsoup4

      - name: Botu Calistir
        run: python fiyat_botu.py

      - name: Sonuclari Otomatik Kaydet
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Otomatik fiyat ve hafiza guncellendi"
          file_pattern: "fiyatlar.txt urun_durum.json"
